name: geominder
description: "A location-based alarm application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1
  # Packages for background and notifications
  flutter_background_service: ^5.0.5
  flutter_local_notifications: ^17.1.2

  # Firebase Packages
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2

  # Other Packages
  shared_preferences: ^2.2.3
  http: ^1.2.1
  flutter_map: ^6.1.0
  geolocator: ^12.0.0
  uuid: ^4.4.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true