// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3u6K_2NWmRvq9HZvsWEqt4Bj2_RPGmD4',
    appId: '1:389480426521:web:074c38968f8d482b22ce88',
    messagingSenderId: '389480426521',
    projectId: 'geominder-app-5b51c',
    authDomain: 'geominder-app-5b51c.firebaseapp.com',
    storageBucket: 'geominder-app-5b51c.firebasestorage.app',
    measurementId: 'G-YKV41TRE6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcZkgHJqLmIaayvpv-kN65Dxm6kjve8Gg',
    appId: '1:389480426521:android:4141ce1dfc89dccc22ce88',
    messagingSenderId: '389480426521',
    projectId: 'geominder-app-5b51c',
    storageBucket: 'geominder-app-5b51c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMMZN8OEitimGOcfx195SvILxKZqDwTik',
    appId: '1:389480426521:ios:3bd6e6e86139b13122ce88',
    messagingSenderId: '389480426521',
    projectId: 'geominder-app-5b51c',
    storageBucket: 'geominder-app-5b51c.firebasestorage.app',
    iosBundleId: 'com.example.geominder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMMZN8OEitimGOcfx195SvILxKZqDwTik',
    appId: '1:389480426521:ios:3bd6e6e86139b13122ce88',
    messagingSenderId: '389480426521',
    projectId: 'geominder-app-5b51c',
    storageBucket: 'geominder-app-5b51c.firebasestorage.app',
    iosBundleId: 'com.example.geominder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3u6K_2NWmRvq9HZvsWEqt4Bj2_RPGmD4',
    appId: '1:389480426521:web:d6edf581c3ed1de222ce88',
    messagingSenderId: '389480426521',
    projectId: 'geominder-app-5b51c',
    authDomain: 'geominder-app-5b51c.firebaseapp.com',
    storageBucket: 'geominder-app-5b51c.firebasestorage.app',
    measurementId: 'G-FZGGMEK62D',
  );

}